version: '3'

services:
  nginx-upstream:
    container_name: ${PROJECT_NAME}-nginx-upstream
    image: nginx:alpine
    volumes:
      - ./docker/nginx/load_balancer.nginx:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "8080:80"

  nginx1:
    container_name: ${PROJECT_NAME}-nginx1
    image: nginx:alpine
    working_dir: /app
    volumes:
      - socket1:/var/run
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./app:/app
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm1

  php-fpm1:
    container_name: ${PROJECT_NAME}-php-fpm1
    build:
      context: ./docker/php-fpm
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - socket1:/var/run
      - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-dev.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./app:/app
    restart: always
    env_file:
      - .env

  nginx2:
    container_name: ${PROJECT_NAME}-nginx2
    image: nginx:alpine
    working_dir: /app
    volumes:
      - socket2:/var/run
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./app:/app
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - php-fpm2

  php-fpm2:
    container_name: ${PROJECT_NAME}-php-fpm2
    build:
      context: ./docker/php-fpm
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - socket2:/var/run
      - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-dev.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./app:/app
    restart: always
    env_file:
      - .env

volumes:
  socket1:
  socket2:

