 
version: '3.6'

services:
  nginx:
    build:
      context: ./
      dockerfile: nginx/dockerfile
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    volumes:
      - ./www:/usr/share/nginx/html

  php-fpm:
    build:
      context: ./
      dockerfile: php-fpm/dockerfile
    ports:
      - 9000:9000
