version: "3"

services:
    webserver1:
        build: ./server/php
        ports:
            - 81:80
        working_dir: /var/app
        volumes:
            - ./server/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/app
    webserver2:
        build: ./server/php
        ports:
            - 80:80
        working_dir: /var/app
        volumes:
            - ./server/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/app
