version: '3.3'

services:

  otus-nginx:
    image: nginx:1.15
    ports:
      - '6060:80'
    depends_on:
      - otus-php
    networks:
      - shared
    volumes:
      - ./otus/www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  otus-php:
    build: ./otus
    ports:
      - '9000:9000'
    container_name: otus-php
    networks:
      - shared
    depends_on:
      - otus-redis
    volumes:
      - ./otus/www:/var/www/html

networks:
  shared:
    driver: bridge
