version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "802:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
      - socket:/var/run
    links:
      - php

  php:
    build: ./docker/php/
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./config/php.www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/var/run
    env_file:
      - ./.env
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    hostname: php-rabbit
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./docker/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  socket: