version: '3'

services:
    nginx:
        container_name: otus-php-nginx
        build:
            context: ./docker
            dockerfile: nginx.docker
        ports:
            - 8081:80
        volumes:
            - ./:/var/www

    php:
        container_name: otus-php-php
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
