version: '3.6'
services:
  php:
    build:
      context: ./docker/php
      args:
        UID: "3000"
    volumes:
      - ./sock:/sock
      - ./app:/data/app:ro
  nginx:
    build:
      context: ./docker/nginx
      args:
        UID: "3000"
    ports:
      - "8080:80"
    volumes:
      - ./sock:/sock
      - ./app:/data/app:ro
    links:
      - php
    depends_on:
      - php