version: '3.3'

services:

  otus-nginx:
    image: nginx:1.15
    ports:
      - '6060:80'
    depends_on:
      - otus-php
    networks:
      - shared
    volumes:
      - ./otus/www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  otus-php:
    build: ./otus
    ports:
      - '9000:9000'
    container_name: otus-php
    networks:
      - shared
    depends_on:
      - otus-redis
    volumes:
      - ./otus/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./otus/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./otus/www:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  otus-redis:
    image: redis:alpine
    container_name: otus-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - shared
    ports:
      - 6380:6380

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE="youtube"
    volumes:
      - ./dbdata/db:/var/mongodb/data
    ports:
      - 27017:27017
    networks:
      - shared

networks:
  shared:
    driver: bridge

volumes:
  redis-data:
