version: '3'
services:
  app:
    container_name: vlyagusha-app
    build: docker/php
    volumes:
      - ./:/home/www/mysite.local

  nginx:
    container_name: vlyagusha-nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/home/www/mysite.local
      - ./docker/nginx/mysite.local.conf:/etc/nginx/conf.d/mysite.local.conf
    depends_on:
      - app