version: "2"

networks:
  default:
    external:
      name: nginx-proxy

services:
  nginx-balancer:
    container_name: nginx-balancer
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.balancer
    ports:
    - 8081:8081
    restart: always