version: '3'
services:
    app:
        container_name: app
        build: .
        volumes:
            - .:/app
            - ./php.dev.ini:/usr/local/etc/php/php.ini
        command: php /app/index.php --server
        environment:
            - CLIENT_DEFAULT_MESSAGE='None'
