version: "3.6"
services:
  php-cli73:
    container_name: "php-cli73-container"
    restart: unless-stopped
    image: wolodin/php73-fpm-debian:latest
    volumes:
      - "./socks:/socks:rw"
      - "./tools:/tools:ro"
      - "./code:/home/web/code:rw,cached"
    entrypoint: ["/tools/php-entrypoint.sh"]
    command: ["php", "-f", "/home/web/code/test.php"]
    environment:
      HOST_USER_ID: "${HOST_USER_ID:-1000}"
      HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
    working_dir: "/home/web"
    networks:
      - webnet

networks:
  webnet:
