version: "3"

services:
    app:
        build: ./docker
        container_name: 'capistrano'
        command: tail -f /dev/null
        volumes:
            - ./:/var/capistrano
        working_dir: /var/capistrano
