version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - .:/app
      - ./docker/app/conf/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/app/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file:
      - ./dev.env
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
    depends_on:
      - db
    command: tail -f /dev/null
  db:
    container_name: mongo
    image: edmitry/mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
volumes:
  mongo_data:
    external: true
