version: '3'
services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - socks:/socks
      - ./docker/app/conf/php/preload.ini:/usr/local/etc/php/conf.d/preload.ini
    env_file:
      - ./.env
    environment:
      - PHAN_DISABLE_XDEBUG_WARN=1
      - PHAN_ALLOW_XDEBUG=0
      - PHP_IDE_CONFIG=serverName=app
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-fI", "nginx"]
      interval: 1s
      timeout: 1s
      retries: 10
  nginx:
    container_name: nginx
    image: edmitry/nginx
    restart: always
    volumes:
      - socks:/socks
      - ./public:/web
    ports:
      - 80:80
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost/nginx-status"]
      interval: 1s
      timeout: 1s
      retries: 10
  redis:
    container_name: redis
    image: edmitry/redis
    restart: always
    volumes:
      - socks:/socks
      - redis_data:/data
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
    sysctls:
      net.core.somaxconn: '511'
volumes:
  socks:
  redis_data:
    external: true
