version: '3'

services:
  nginx:
    networks:
      - code-network
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www/html
      - ./logs:/var/log/nginx
      - phpsocket:/var/run
    links:
      - php

  php:
    networks:
      - code-network
    image: php:7.3-fpm
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.conf:/usr/local/etc/php-fpm.d/php.conf
      - phpsocket:/var/run

networks:
  code-network:
    driver: bridge

volumes:
  phpsocket: