version: '3.7'
services:
  postgresql-hw8:
    image: postgres:latest
    ports:
      - 54320:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/var/lib/postgresql/docker-entrypoint-initdb.d
      - ./some_scripts:/some_scripts
    environment:
      POSTGRES_PASSWORD: 'password'