version: "3.6"
services:
  nginx:
    container_name: "nginx-container"
    restart: unless-stopped
    image: wolodin/lemp-nginx:latest
    volumes:
      - ./web:/home/projects-data/web:rw
      - ./tools:/tools:ro
    entrypoint: '/tools/web-entrypoint.sh'
    environment:
      VOLUME: '/home/projects-data'
      DOCKER_USER: 'projects-data'
      DOCKER_GROUP: 'projects-data'
      HOST_USER_ID: 1000
      HOST_GROUP_ID: 1000
    ports:
      - "127.0.0.1:80:8080"
    networks:
      - webnet

networks:
  webnet:
