version: "3.6"
services:
  frontend:
    container_name: "nginx-container"
    restart: unless-stopped
    image: wolodin/lemp-nginx:latest
    volumes:
      - "./tools:/tools:ro"
      - "./socks:/socks:rw"
      - "./config/nginx/sites-enabled:/etc/nginx/sites-enabled.ro:ro"
      - "./mysite.local:/home/web/www/mysite.local:rw,cached"
    entrypoint: ["/tools/web-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    working_dir: "/home/web"
#    depends_on:
#      - php
    environment:
      HOST_USER_ID: "1000"
      HOST_GROUP_ID: "1000"
    ports:
      - "127.0.0.1:80:8080"
    networks:
      - webnet
    extra_hosts:
      - "mysite.local:127.0.0.1"

networks:
  webnet:
