version: '3'
services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../project/public:/var/www/site/public
      - ../conf/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../project:/var/www/site/
