index:
    path: /
    controller: Bjlag\Controllers\IndexController
    methods: [GET]
    defaults: {_action: 'process'}

check-email:
    path: /check-email
    controller: Bjlag\Controllers\CheckEmailController
    methods: [GET]
    defaults: {_action: 'process'}
#    requirements:
#        name: '\w+'
