version: '3'

services:

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app/public_html:/var/www/app.local/public_html
      - phpsocket:/run/php

  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./app/public_html:/var/www/app.local/public_html
      - ./docker/nginx/app.local.conf:/etc/nginx/conf.d/app.local.conf
      - phpsocket:/run/php
    depends_on:
      - php
volumes:
  phpsocket:
