version: '3'

services:

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/app.local
      - phpsocket:/var/run

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app.local
      - ./docker/nginx/app.local.conf:/etc/nginx/conf.d/app.local.conf
      - phpsocket:/var/run
    depends_on:
      - php
volumes:
  phpsocket:
