version: "2"

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  socket2:

services:
  app2:
    container_name: app2
    build:
      context: ../../
      dockerfile: ./php/Dockerfile
    volumes:
    - socket2:/var/run/php
    - ../../php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - ../../app:/var/www/otus
    restart: always

  nginx2:
    container_name: node2
    build:
      context: ../../
      dockerfile: ./nginx/Dockerfile
    volumes:
    - socket2:/var/run/php
    depends_on:
      - app2
    restart: always