version: "3"

services:
        php:
                build: ./php
                volumes:
                        - ./site/:/app/
                        - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
                        - ./php/sock/:/sock/
        nginx:
                build: ./nginx
                volumes:
                        - ./php/sock/:/sock/
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                        - ./site/:/usr/share/nginx/html/
                ports:
                        - 80:80

