version: '3'
services:
  php:
    build:
      context: php
    expose:
      - 9000
    volumes:
      - ../src:/var/www/ushakov
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
  nginx:
    build:
      context: nginx
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/ushakov
      - ./nginx/nginx.conf:/etc/nginx/conf.d/ushakov.conf
