---
- name: Download Composer
  script: scripts/install_composer.sh

- name: Move Composer globally
  become: true
  command: mv composer.phar /usr/local/bin/composer

- name: Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"