version: "2"

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  socket3:

services:
  app3:
    container_name: app3
    build:
      context: ../../
      dockerfile: ./php/Dockerfile
    volumes:
    - socket3:/var/run/php
    - ../../php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - ../../app:/var/www/otus
    restart: always

  nginx3:
    container_name: node3
    build:
      context: ../../
      dockerfile: ./nginx/Dockerfile
    volumes:
    - socket3:/var/run/php
    depends_on:
      - app3
    restart: always